### ISSUE TITLE
F-900 F.A.Q. has mismatching fonts

### ISSUE THREAD

**Issue by rahiensorei21** [CIDBioScience/felix.com#157]
On the F-900 F.A.Q. http://www.felixinstruments.com/support/f-900-support/f-a-q, some of the fonts used for answers do not match the font used for the other answers. 
![image](https://cloud.githubusercontent.com/assets/13140691/12855360/cd710eb6-cbf3-11e5-9829-51b315b3ee7f.png)

Specifically, the mismatching fonts are the answers to the questions "How is Chamber In used to rehydrate the electrochemical cell?" and "What type of material is used in the anode of the F-900 electrochemical sensor?"

**Comment by loreguerra** [comment]
This is an ongoing issue since we have different contributors to the site and Joomla makes no attempt to work efficiently whatsoever. 

When someone pastes copy into the editor, they should be clicking on the "Format" menu and then "clear formatting".

Just FYI for anyone who reads this.

I fixed the text and will check the other FAQ sections. Thank you for pointing it out!
